import { Header } from '@/components/header'
import type { Metadata } from 'next'
import { DM_Sans, Poppins, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { Footer } from '@/components/footer'

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
})

const poppins = Poppins({
  weight: ['400'],
  variable: '--font-poppins',
  subsets: ['latin'],
})

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ['400'],
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${poppins.variable} ${plusJakartaSans.variable} antialiased`}
    >
      <body className="font-primary text-text">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
